language: cpp

jobs:
  include:
    - os: linux
      compiler: g++
      dist: bionic
      sudo: required
      install: 
        - sh ./platform/emscripten/setup_emsdk.sh 
      script:
        - sh ./build_emscripten.sh

    - os: osx
      osx_image: xcode11.5
      sudo: required 
      install: 
      script:
        - sh ./build_mac.sh
        - sh ./build_ios_simulator.sh
        - sh ./build_ios.sh
