name: windows_ci
on:
  push:
    branches:
      - main 

  pull_request:

  schedule:
      - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:
    runs-on: windows-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4
    steps:
      - name: Build
        shell: powershell
        run: |
          .\build_windows.bat
