name: windows_build
on:
  push:
    branches:
      - main 

  pull_request:

  schedule:
      - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:
    runs-on: windows-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Build
        shell: powershell
        run: |
          .\build_windows.bat
